from pathlib import Path

services:
  - type: web
    name: api-credit-scoring-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000

# Sauvegarde dans un fichier .yaml
output_path = Path("/mnt/data/render.yaml")
output_path.write_text(render_yaml_content)

output_path.name
Résultat
'render.yaml'
